// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.10.0
// source: client.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogClientServiceClient is the client API for LogClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogClientServiceClient interface {
	GetClients(ctx context.Context, in *LogClientsQuery, opts ...grpc.CallOption) (*LogClientsResult, error)
	GetDatabases(ctx context.Context, in *DatabasesQuery, opts ...grpc.CallOption) (*DatabasesResult, error)
	GetTables(ctx context.Context, in *TablesQuery, opts ...grpc.CallOption) (*TablesResult, error)
}

type logClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClientServiceClient(cc grpc.ClientConnInterface) LogClientServiceClient {
	return &logClientServiceClient{cc}
}

func (c *logClientServiceClient) GetClients(ctx context.Context, in *LogClientsQuery, opts ...grpc.CallOption) (*LogClientsResult, error) {
	out := new(LogClientsResult)
	err := c.cc.Invoke(ctx, "/model.LogClientService/GetClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClientServiceClient) GetDatabases(ctx context.Context, in *DatabasesQuery, opts ...grpc.CallOption) (*DatabasesResult, error) {
	out := new(DatabasesResult)
	err := c.cc.Invoke(ctx, "/model.LogClientService/GetDatabases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClientServiceClient) GetTables(ctx context.Context, in *TablesQuery, opts ...grpc.CallOption) (*TablesResult, error) {
	out := new(TablesResult)
	err := c.cc.Invoke(ctx, "/model.LogClientService/GetTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogClientServiceServer is the server API for LogClientService service.
// All implementations should embed UnimplementedLogClientServiceServer
// for forward compatibility
type LogClientServiceServer interface {
	GetClients(context.Context, *LogClientsQuery) (*LogClientsResult, error)
	GetDatabases(context.Context, *DatabasesQuery) (*DatabasesResult, error)
	GetTables(context.Context, *TablesQuery) (*TablesResult, error)
}

// UnimplementedLogClientServiceServer should be embedded to have forward compatible implementations.
type UnimplementedLogClientServiceServer struct {
}

func (UnimplementedLogClientServiceServer) GetClients(context.Context, *LogClientsQuery) (*LogClientsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (UnimplementedLogClientServiceServer) GetDatabases(context.Context, *DatabasesQuery) (*DatabasesResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabases not implemented")
}
func (UnimplementedLogClientServiceServer) GetTables(context.Context, *TablesQuery) (*TablesResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTables not implemented")
}

// UnsafeLogClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogClientServiceServer will
// result in compilation errors.
type UnsafeLogClientServiceServer interface {
	mustEmbedUnimplementedLogClientServiceServer()
}

func RegisterLogClientServiceServer(s grpc.ServiceRegistrar, srv LogClientServiceServer) {
	s.RegisterService(&LogClientService_ServiceDesc, srv)
}

func _LogClientService_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogClientsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogClientServiceServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.LogClientService/GetClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogClientServiceServer).GetClients(ctx, req.(*LogClientsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogClientService_GetDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabasesQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogClientServiceServer).GetDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.LogClientService/GetDatabases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogClientServiceServer).GetDatabases(ctx, req.(*DatabasesQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogClientService_GetTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TablesQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogClientServiceServer).GetTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.LogClientService/GetTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogClientServiceServer).GetTables(ctx, req.(*TablesQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// LogClientService_ServiceDesc is the grpc.ServiceDesc for LogClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.LogClientService",
	HandlerType: (*LogClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClients",
			Handler:    _LogClientService_GetClients_Handler,
		},
		{
			MethodName: "GetDatabases",
			Handler:    _LogClientService_GetDatabases_Handler,
		},
		{
			MethodName: "GetTables",
			Handler:    _LogClientService_GetTables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
