// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.10.0
// source: logs.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogEntryServiceClient is the client API for LogEntryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogEntryServiceClient interface {
	Write(ctx context.Context, in *WriteLogCommand, opts ...grpc.CallOption) (*LogEntryResult, error)
}

type logEntryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogEntryServiceClient(cc grpc.ClientConnInterface) LogEntryServiceClient {
	return &logEntryServiceClient{cc}
}

func (c *logEntryServiceClient) Write(ctx context.Context, in *WriteLogCommand, opts ...grpc.CallOption) (*LogEntryResult, error) {
	out := new(LogEntryResult)
	err := c.cc.Invoke(ctx, "/model.LogEntryService/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogEntryServiceServer is the server API for LogEntryService service.
// All implementations should embed UnimplementedLogEntryServiceServer
// for forward compatibility
type LogEntryServiceServer interface {
	Write(context.Context, *WriteLogCommand) (*LogEntryResult, error)
}

// UnimplementedLogEntryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedLogEntryServiceServer struct {
}

func (UnimplementedLogEntryServiceServer) Write(context.Context, *WriteLogCommand) (*LogEntryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}

// UnsafeLogEntryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogEntryServiceServer will
// result in compilation errors.
type UnsafeLogEntryServiceServer interface {
	mustEmbedUnimplementedLogEntryServiceServer()
}

func RegisterLogEntryServiceServer(s grpc.ServiceRegistrar, srv LogEntryServiceServer) {
	s.RegisterService(&LogEntryService_ServiceDesc, srv)
}

func _LogEntryService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteLogCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogEntryServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.LogEntryService/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogEntryServiceServer).Write(ctx, req.(*WriteLogCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// LogEntryService_ServiceDesc is the grpc.ServiceDesc for LogEntryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogEntryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.LogEntryService",
	HandlerType: (*LogEntryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _LogEntryService_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
